version: '3.7'
services:
  question-service:
    image: ${GROUP_ID}/question.service:${SERVICE_VERSION}
    ports:
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/question-service/logs"
    networks:
      - ${GLOBAL_NETWORK:-services}

networks:
  application:
    external:
      name: ${GLOBAL_NETWORK}
