server:
  port: 9297

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DraganovTs/config-server-quiz-app.git
          clone-on-start: true
